development:
  adapter: postgresql
  encoding: unicode
  database: listtxt_dev
  pool: 5
  username: alexanderlewis
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: listtxt_test
  pool: 5
  username: alexanderlewis
  password:
